# -*- coding: utf-8 -*-
"""city_name_unification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zuE5pLIKAQ5K_yEZlXbb1mzjX6et8b0o
"""

import pandas as pd
import re

# 1. 데이터 불러오기
hospital_df = pd.read_csv("bohun_hospital_final.csv", encoding="cp949")
veteran_df = pd.read_csv("veteran_population_by_region.csv")

# 2. 상세주소에서 '구' 또는 '군' 추출
def extract_gu(address):
    if pd.isna(address):
        return None
    match = re.search(r'(\S+[구군])', address)
    return match.group(1) if match else None

# 3. 병원 데이터 지역키 생성: 시군구명 + 상세주소에서 추출한 구명 (공백 제거)
hospital_df['병원_지역키'] = hospital_df['시군구명'].str.replace(r'\s+', '', regex=True) + \
                             hospital_df['구_상세주소'].fillna('')

# 4. 보훈 데이터의 시군구명에서 괄호 내용 제거
def clean_area(area):
    return re.sub(r"\s*\(.*?\)", "", str(area)).strip()

veteran_df['veteran_지역키'] = veteran_df['시군구명'].apply(clean_area).str.replace(r'\s+', '', regex=True)

# 5. 병원 통계 집계
hospital_stats = hospital_df.groupby('병원_지역키').agg(
    병원수=('위탁병원명', 'count'),
    진료과수_평균=('진료과수', 'mean')
).reset_index()

# 👉 정수로 반올림
hospital_stats['진료과수_평균'] = hospital_stats['진료과수_평균'].round().astype(int)

# 6. 병합
merged_df = pd.merge(veteran_df, hospital_stats, how='left',
                     left_on='veteran_지역키', right_on='병원_지역키')

# 7. 결과 저장
merged_df[['지역명', '시군구명', '보훈대상자수', '병원수', '진료과수_평균']].to_excel("보훈_병원_통계_최종결과.xlsx", index=False)