# -*- coding: utf-8 -*-
"""distance_bohun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujD9WYemNXYxe42Ffz6XRPKsYd91ede3
"""

!pip install googlemaps tqdm

import pandas as pd
import googlemaps
from tqdm import tqdm

# 너의 API 키를 여기에 붙여넣기
gmaps = googlemaps.Client(key='AIzaSyBH5QUc6gxoyrXCa3MRjk7oXNx_NHCCooc')

# 데이터 불러오기
df = pd.read_csv("bohun_hospital_all.csv")

# 구청 주소 생성
df['구청주소'] = df['광역시도명'] + ' ' + df['시군구명'] + '청'

df.head()

# 거리 계산 결과 저장용
df['대중교통거리_km'] = None
df['대중교통시간'] = None

# 거리 계산 함수
def get_transit_distance(origin, destination):
    try:
        result = gmaps.distance_matrix(
            origins=origin,
            destinations=destination,
            mode='transit',
            language='ko',
            departure_time='now'
        )
        element = result['rows'][0]['elements'][0]
        if element['status'] == 'OK':
            dist_km = element['distance']['value'] / 1000  # m → km
            duration = element['duration']['text']
            return dist_km, duration
        else:
            return None, element['status']
    except Exception as e:
        return None, str(e)

# 거리 계산 적용
tqdm.pandas()
df[['대중교통거리_km', '대중교통시간']] = df.progress_apply(
    lambda row: pd.Series(get_transit_distance(row['상세주소'], row['구청주소'])),
    axis=1
)

# 시간 단위(ex.23분, 1시간 14분)을 모두 숫자(ex.23, 74)로 변환하는 함수
import re

def clean_and_average_time_v2(time_str):
    if pd.isna(time_str):
        return None

    time_str = str(time_str).replace('NOT_FOUND', '')
    pattern = r'(?:(\d+)시간)?\s*(\d+)분'  # 정규표현식: "1시간 15분", "23분", "2시간" 등

    matches = re.findall(pattern, time_str)
    times = []

    for hour, minute in matches:
        hour = int(hour) if hour else 0
        minute = int(minute) if minute else 0
        total_minutes = hour * 60 + minute
        times.append(total_minutes)

    return sum(times) / len(times) if times else None

df['대중교통시간_분'] = df['대중교통시간'].apply(clean_and_average_time_v2)
access_df = df.groupby(['광역시도명', '시군구명'])['대중교통시간_분'].mean().reset_index()

access_df

access_df.to_excel("시군구별_접근성_평균_final.xlsx", index=False)