# -*- coding: utf-8 -*-
"""distance_bohun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fm3R1NFgJtyg86Jq8RBbnpd_ROTjaMmr
"""

!pip install googlemaps tqdm

import pandas as pd
import googlemaps
from tqdm import tqdm

# 너의 API 키를 여기에 붙여넣기
gmaps = googlemaps.Client(key='...')

# 데이터 불러오기
df = pd.read_csv("bohun_hospital_final.csv")

# 구청 주소 생성
df['구청주소'] = df['지역명'] + ' ' + df['시군구명'] + '청'

# 거리 계산 결과 저장용
df['대중교통거리_km'] = None
df['대중교통시간'] = None

# 거리 계산 함수
def get_transit_distance(origin, destination):
    try:
        result = gmaps.distance_matrix(
            origins=origin,
            destinations=destination,
            mode='transit',
            language='ko',
            departure_time='now'
        )
        element = result['rows'][0]['elements'][0]
        if element['status'] == 'OK':
            dist_km = element['distance']['value'] / 1000  # m → km
            duration = element['duration']['text']
            return dist_km, duration
        else:
            return None, element['status']
    except Exception as e:
        return None, str(e)

# 주소 결합 + 거리 계산 적용
df[['대중교통거리_km', '대중교통시간']] = df.progress_apply(
    lambda row: pd.Series(
        get_transit_distance(f"{row['지역명']} {row['시군구명']} {row['상세주소']}", row['구청주소'])
    ),
    axis=1
)

# 거리 계산 적용
tqdm.pandas()
df[['대중교통거리_km', '대중교통시간']] = df.progress_apply(
    lambda row: pd.Series(get_transit_distance(row['상세주소'], row['구청주소'])),
    axis=1
)

# 시군구별 평균 거리 계산
access_df = df.groupby(['지역명', '시군구명'])['대중교통거리_km'].mean().reset_index()
access_df.rename(columns={'대중교통거리_km': '평균_대중교통_거리_km'}, inplace=True)

# 저장
df.to_excel("hospital_accessibility.xlsx", index=False)